version: '3'
services:
  service1:
    build:
      context: .
      dockerfile: service1/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - media_data:/media
    working_dir: /media
    command: ["python3", "/app/service1.py"]

  service2:
    build: ./service2
    ports:
      - "3002:3002"
    volumes:
      - media_data:/media
    working_dir: /media
    command: ["python3", "/app/service2.py"]

  service3:
    build: ./service3
    ports:
      - "3003:3003"
    volumes:
      - media_data:/media
    working_dir: /media
    command: ["python3", "/app/service3.py"]

  service4:
    build: ./service4
    ports:
      - "3004:3004"

  service5:
    build: ./service5
    ports:
      - "3005:3005"

volumes:
  media_data:

