version: '3.8'

services:
  service1:
    container_name: transcribe_service
    build:
      context: ./service1
    ports:
      - "3001:3001"
    volumes:
      - ./service1:/app
      - media_data:/data
    restart: unless-stopped

  service2:
    container_name: clipper_service
    build:
      context: ./service2
    ports:
      - "3002:3002"
    volumes:
      - ./service2:/app
      - media_data:/data
    restart: unless-stopped

  service3:
    container_name: editor_service
    build:
      context: ./service3
    ports:
      - "3003:3003"
    volumes:
      - ./service3:/app
      - media_data:/data
    restart: unless-stopped

  service4:
    container_name: publish_shorts_service
    build:
      context: ./service4
    ports:
      - "3004:3004"
    volumes:
      - ./service4:/app
      - media_data:/data
    restart: unless-stopped

  service5:
    container_name: publish_long_service
    build:
      context: ./service5
    ports:
      - "3005:3005"
    volumes:
      - ./service5:/app
      - media_data:/data
    restart: unless-stopped

volumes:
  media_data:
