version: '3'
services:
  service1:
  build: ./service1          # context set to the folder
  ports:
    - "3001:3001"
  volumes:
    - media_data:/data
    ports:
      - "3001:3001"
    volumes:
      - media_data:/data
  service2:
    build: ./service2
    ports:
      - "3002:3002"
    volumes:
      - media_data:/data
  service3:
    build: ./service3
    ports:
      - "3003:3003"
    volumes:
      - media_data:/data
  service4:
    build: ./service4
    ports:
      - "3004:3004"

  service5:
    build: ./service5
    ports:
      - "3005:3005"
volumes:
  media_data:
